### ISSUE TITLE
Chainlink security contact

### ISSUE THREAD

**Issue by kaleofduty** [crytic/blockchain-security-contacts#111]
Hey there!
Please update the Chainlink security contact to security@chain.link

We don't have it on our website currently, so it would probably be easiest if you email us a challenge nonce which we can post in this issue to verify it is working.

**Comment by dguido** [comment]
https://github.com/crytic/blockchain-security-contacts/commit/f6918608d3b9e0e99f918be38a73d5fec6cafa2f
